[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[window]
padding = { x = 16, y = 16 }
dynamic_padding = true
decorations = "None"
opacity = 0.64
blur = true
startup_mode = "SimpleFullScreen"
resize_increments = false

[font]
size = 12.0
normal      = { family = "MesloLGSDZ Nerd Font", style = "Regular" }
bold        = { family = "MesloLGSDZ Nerd Font", style = "Bold" }
italic      = { family = "MesloLGSDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGSDZ Nerd Font", style = "Bold Italic" }

# [bell]
# animation = "EaseOutSine"
# duration = 256
# color = "#C0C5CE"

[selection]
save_to_clipboard = true

[cursor]

    [cursor.style]
    blinking = "On"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "F", mods = "Command", action = "ToggleSimpleFullscreen" },
    { key = "N", mods = "Command", action = "CreateNewWindow" }
]
