[colors]

    [colors.primary]
    foreground = "#d8dee9"
    background = "#2e3440"
    dim_foreground = "#a5abb6"

    [colors.cursor]
    text = "#2e3440"
    cursor = "#81a1c1"

    [colors.selection]
    background = "#4c566a"
    text = "CellForeground"

    [colors.normal]
    black = "#3b4252"
    blue = "#81a1c1"
    cyan = "#88c0d0"
    green = "#a3be8c"
    magenta = "#b48ead"
    red = "#bf616a"
    white = "#e5e9f0"
    yellow = "#ebcb8b"

    [colors.bright]
    black = "#4c566a"
    blue = "#81a1c1"
    cyan = "#8fbcbb"
    green = "#a3be8c"
    magenta = "#b48ead"
    red = "#bf616a"
    white = "#eceff4"
    yellow = "#ebcb8b"

